# azure-pipelines.yml
trigger:
  - main

pool:
  vmImage: 'windows-latest'  # Changed to Windows

steps:
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'app'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
